name: "YouTrack Sync"
description: "Syncs YouTrack with your pull requests"
inputs:
  github-token:
    description: "GitHub Token"
    required: true
  yt-project-id:
    description: "Issue ID prefix used in the projects"
    required: true
  yt-url:
    description: "Base URL of your YouTrack instance"
    required: true
    default: "https://my-yt.myjetbrains.com/youtrack"
  yt-token:
    description: "Youtrack permanent token"
    required: true
  yt-column-field:
    description: "Youtrack column name type"
    default: "Stage"
  yt-column-triggers:
    description: "Youtrack column names that trigger the action"
    default: "To Do, To Fix, In Progress"
  yt-column-target:
    description: "Youtrack column name to move issues on PR open"
    default: "PR Open"
  yt-label-fields:
    description: "Youtrack fields from which label the PR"
    default: "Type, Priority"
  yt-label-prefix:
    description: "String to prefix your labels with"
branding:
  icon: "refresh-cw"
  color: "gray-dark"
runs:
  using: "node12"
  main: "dist/index.js"
